### ISSUE TITLE
Document project structure 

### ISSUE THREAD

**Issue by owitiA** [kudobuzz/express-api-starter#30]
#### PreSubmission Checklist
- [x] The necessary labels have added
- [x] I have assigned issues to the right project

#### Issue Summary
This documents layout and structure of the project. and how the flow of the project should be 

#### Acceptance Criteria 
- [ ] Complete layout of project structure 
- [ ] Clearly explains each segment in project Structure

**Comment by obengwilliam** [comment]
@owitiA  Please update the issue description dont leave it empty

**Comment by owitiA** [comment]
added to the docs files

**Comment by owitiA** [comment]
made changes to review commits

**Comment by owitiA** [comment]
@obengwilliam  in each folder in the project structure do i update the readMe as well

**Comment by obengwilliam** [comment]
>@obengwilliam in each folder in the project structure do i update the readMe as well

if you think that will help

**Comment by obengwilliam** [comment]
@owitiA if you think that will help yeah you can

**Comment by obengwilliam** [comment]
@owitiA  kindly assign the issue to yourself too

**Comment by owitiA** [comment]
Ok
