### ISSUE TITLE
Document API to Open api 3.0.0

### ISSUE THREAD

**Issue by owitiA** [kudobuzz/express-api-starter#32]
#### PreSubmission Checklist
- [x] The necessary labels have added
- [x] I have assigned issues to the right project

#### Issue Summary
This documents the API to fit the api description format of  open API 3.0

**Comment by owitiA** [comment]
@obengwilliam do i document the open API specs

**Comment by owitiA** [comment]
did  a brief example, hopefully that is what was required

**Comment by obengwilliam** [comment]
>@obengwilliam i need a quick clarification ,do i document the open API specs

please if you are not clear on an issue i think u dont have to work on it

**Comment by obengwilliam** [comment]
first we need to define what kind api we will have in this boilerplate to make it easy for everyone to understand how api's should be built. 
What we can do is have a todo api

1. POST todo
2. PUT todo
3. GET todo
4. GET todo/:todoid

**Comment by obengwilliam** [comment]
you would have come up with the request and response details

**Comment by owitiA** [comment]
> first we need to define what kind api we will have in this boilerplate to make it easy for everyone to understand how api's should be built.
> What we can do is have a todo api
> 
> 1. POST todo
> 2. PUT todo
> 3. GET todo
> 4. GET todo/:todoid

this has another issue created for it

**Comment by obengwilliam** [comment]
@owitiA  so what is this issue about ?

**Comment by owitiA** [comment]
it is one of the deliverables from the epic

**Comment by obengwilliam** [comment]
>it is one of the deliverables from the epic

what i am trying to ask is what is it suppose to do ?

**Comment by obengwilliam** [comment]
since you started working on it

**Comment by owitiA** [comment]
from my understanding i thought it was supposed to help the dev understand the open API and then write their own API so that it follows our example
