### ISSUE TITLE
Document API 

### ISSUE THREAD

**Issue by owitiA** [kudobuzz/express-api-starter#33]
#### PreSubmission Checklist
- [x] The necessary labels have added
- [x] I have assigned issues to the right project

#### Issue Summary
 - [ ] Document Api 
 - [ ] Document api in openapi 3.0.0

**Comment by obengwilliam** [comment]
@owitiA  what is the update on the document
We need to finish this latest by this week else we are not making any headway here

**Comment by owitiA** [comment]
if i tackle this issue because it is related to the health route and writing the tests for api and workers then  we shall be able to finish by this week

**Comment by obengwilliam** [comment]
>if i tackle this issue because it is related to the health route and writing the tests for api and workers then we shall be able to finish by this week

i think i have mentioned this a number of times, finish the documentation first b4 working on the implementation

**Comment by obengwilliam** [comment]
Also if the issue will take more than a day do break it down into smaller issues
