### ISSUE TITLE
Add  express Api starter to codeship

### ISSUE THREAD

**Issue by owitiA** [kudobuzz/express-api-starter#39]
#### PreSubmission Checklist
- [ ] The necessary labels have added
- [ ] I have assigned issues to the right project

#### Issue Summary
once i push my code check doesn't pass because the project express api starter codeshipcheck fails.

#### Steps to Reproduce if Issue is a Bug?
<!-- 1. This is the first step -- >
2. This is the second step

#### Other Technical details if Needed ?
<!-- Test this in ubuntu only-- >

**Comment by obengwilliam** [comment]
I have removed from codeship until there is a need to add any test
